[package]
name = "objdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
clap = { version = "4.4.7", features = ["cargo"] }
anyhow = "1.0.75"
